name: SpotlessApply

on: 
  pull_request:
    branches: [main]
  
jobs:
  apply_spotless:
    needs: [spotless]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: apply spotless
        run: ./gradlew spotlessApply
      
      - name: commit and push
        run: |
          git config user.name spotless
          git config user.email spotless@github.com
          git add .
          git commit -m"spotlessed"
          git push